### ISSUE TITLE
I can step down on role change 

### ISSUE THREAD

**Issue by ChrisKujawa** [zeebe-io/atomix#120]
**Is your feature request related to a problem? Please describe.**

On Zeebe we have the use case that we install specific things on leaders. If this doesn't work ideally we should step down again. This is currently not possible.

**Describe the solution you'd like**
On the raftPartition for example a method like `stepDown`, which internally delegates to the raft server.

**Describe alternatives you've considered**
There are none.

**Additional context**
On role change listeners we could then call stepDown on the partition, such that we are no longer leader when the complete installation was not successful.

**Comment by npepinpe** [comment]
I think this was done in #130?
