### ISSUE TITLE
Do not silently ignore exceptions when executing raft operations

### ISSUE THREAD

**Issue by deepthidevaki** [zeebe-io/atomix#158]
`SingleThreadContext` used by raft to execute its operations, uses a `ScheduledThreadPoolExecutor` to execute tasks. One problem with it is that, unless we explicitly check the result of the future obtained from scheduling the task, it silently ignores all errors (all `Throwable`) from the task execution. It would be useful to at least log these errors.

**Comment by npepinpe** [comment]
Great catch, this might help in figuring out many things (such as why sometimes we stop receiving snapshots) :+1:
