### ISSUE TITLE
Leader does not sent heartbeats on high load

### ISSUE THREAD

**Issue by ChrisKujawa** [zeebe-io/atomix#40]
**Expected behavior**
I expected that even we write into the primitive non stop the leader is still able to send heartbeats.

**Actual behavior**

It is not able to send heartbeats to all followers, which causes a disruptive cluster.

**How to reproduce:**
Easy to reproduce:

```
  @Test
  public void testThreeNodeManyEvents() throws Throwable {
    createServers(3);

    RaftClient client = createClient();
    TestPrimitive primitive = createPrimitive(client);
    primitive.onEvent(message -> {
      threadAssertNotNull(message);
      resume();
    });

    for (int i = 0; i < 5_000; i++) {
      primitive.sendEvent(true);
    }
    await(10000, 1000);

    final List<MetricFamilySamples> appendMetrics = LeaderMetrics.getAppendMetrics();
    final MetricFamilySamples samples = appendMetrics.get(0);
    final double valueCount = samples.samples.get(15).value;

    // bucket 0.5 should contain all otherwise we have to high latency
    final Sample sample = samples.samples.stream().filter(s -> s.labelValues.contains("0.5")).findFirst().get();
    assertThat(sample.value, is(valueCount));
  }
```
I wrote this test to verify that I didn't increased the latency due some changes but most of the times it fails before because there to much leader changes.

**Comment by npepinpe** [comment]
Was this solved by splitting it into two threads?

**Comment by ChrisKujawa** [comment]
Yes this test is also now available here https://github.com/zeebe-io/atomix/blob/develop/protocols/raft/src/test/java/io/atomix/protocols/raft/RaftTest.java#L1406
