### ISSUE TITLE
Reformat Atomix Code base

### ISSUE THREAD

**Issue by ChrisKujawa** [zeebe-io/atomix#43]
**Is your feature request related to a problem? Please describe.**

It bothers me that I always on build have to fix several formatting issues and they are hidden between tons of warning which the code base has.
I would like to reformat the whole code base either in their formatting or just use our google base format, which would make probably make more sense.

**Comment by npepinpe** [comment]
Can we maybe start with only the Raft module, since I guess it'll be where we do most of our changes?

**Comment by ChrisKujawa** [comment]
done
