### ISSUE TITLE
Directory snapshot support

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/atomix#54]
**Is your feature request related to a problem? Please describe.**

Atomix snapshots are currently a single blob, which makes it easier to manage, but makes it incompatible with RocksDB snapshots. RocksDB snapshots are essentially a copy of the in-memory contents at the time of snapshot, and a series of hard-links to shared immutable SST files. We could pack the RocksDB snapshot folder into a single file, but this means copying everything, which means more disk space usage/slower snapshot time.

Additionally, it would be useful for us to keep our asynchronous snapshot mechanism, and simply generate the snapshots in a format that Atomix can use; this would allow us to use the normal Raft snapshot RPCs and avoid any kind of complex restore procedure.

**Describe the solution you'd like**

Once a new RocksDB snapshot is available, we notify an Atomix-aware component of it, which then adds metadata to the snapshot and adds it to the Atomix snapshot store, such that the snapshot is both usable by the Zeebe engine, and can be replicated to followers by Atomix. On the follower side, on installation, we simply need to ensure that Zeebe is made aware of it such that it can update its logstream (if any) with the latest positions.

**Describe alternatives you've considered**

One alternative is packing our RocksDB snapshots into a normal Atomix `FileSnapshot` using tar or any compression library that preserves directory paths, and unpacking it when installing the snapshot. This is the simplest way, but does not scale very well with snapshot sizes.

Another option is to again add a restore procedure which ensures we have the latest snapshot before joining the Raft; this can be accomplished by joining the cluster as an inactive member and being promoted to active only when the latest snapshot is present.

**Additional context**

**Comment by npepinpe** [comment]
@Zelldon let me know what you think; I'd also like to discuss more in depth the actual implementation and how it'll work with Zeebe, and I think you know our snapshots very well so that'll help

**Comment by ChrisKujawa** [comment]
> we simply need to ensure that Zeebe is made aware of it such that it can update its logstream (if any) with the latest positions.

What do you mean with that? 

Normally the snapshot should only contain our processing related stuff right?

Other than that I think sounds good. Curious about the implementation is hard to tell now whether it is good or not.

**Comment by npepinpe** [comment]
Sorry, it was badly worded, I meant when a follower receives a new snapshot through leader replication (I.e. install rpc) and not our async replication, then we might need to update state on the Zeebe side (e.g. commit position based on snapshot). Maybe I'm wrong and we dont need to do anything, but it feels like we might. That's part of implementation details I want to discuss :sweat_smile:
