### ISSUE TITLE
Split append/replicate from ZeebeLogAppender

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/atomix#74]
**Is your feature request related to a problem? Please describe.**

The current implementation in `ZeebeLogAppender#append` returns a future which completes when the entry has been committed. This enables the back pressure implementation on the Zeebe side in the `LogStorageAppender`, but means throughput is affected as we don't append the next block until it is committed.

**Describe the solution you'd like**

To that extent, we should provide an API such that we can react in both cases:

1. The entry has been written to disk (not sync'd or committed)
1. The entry has been committed

The first case we can move on to the next block and write the next entry. The second case we can release the space for the back pressure.

**Comment by npepinpe** [comment]
@Zelldon : Right now, the append operation both writes to the disk locally, and then replicates it, and the future is completed when we commit the entry. We want to react when it is written locally, and also when it is committed. So I see three options here:

1. Split the append operation into two, `append` and `replicate`, each with their respective future, and the `LogStorageAppender` has to chain them. I'm not a huge fan of this however, and would rather not do this.
1. `append` returns a future which is completed on commit, and we can pass an optional consumer as well which is called when the entry is written locally.
1. `append` returns nothing, and takes a listener interface which has 2 methods: `onWrite` and `onCommit`. The first one is called when we write the entry locally, and the second one when it is committed.

I'd rather do 2 or 3, but I'm not sure which I prefer :thinking:

**Comment by ChrisKujawa** [comment]
Actually I'm not 100% if we still need the back pressure there it might be enough to have the dispatcher as a back pressure mechanism, so future completion on successfully written would be then enough.

The extra back pressure was necessary because atomix and his primitive was not able to handle so much requests/load. After the changes this will be different, because we will directly write without network or routing in between. I think to find the ideal solution we need to benchmark it again .

**Comment by npepinpe** [comment]
After discussing we'll go with the listener option so we can test more easily different approaches.

**Comment by npepinpe** [comment]
Alright, here's a draft of the interface before I start on it, let me know what you think:

```java
/**
 * A log appender provides a central entry point to append to the local Raft log such that it is
 * automatically replicated and eventually committed, and the ability for callers to be notified of
 * various events, e.g. {@link Listener#onCommit(Indexed)}.
 */
@FunctionalInterface
public interface ZeebeLogAppender {

  /**
   * Appends an entry to the local Raft log and schedules replication to each follower.
   *
   * @param lowestPosition lowest record position in the data buffer
   * @param highestPosition highest record position in the data buffer
   * @param data data to store in the entry
   * @param onWrite a consumer which is called when the entry has been written locally; may be null
   * @param onCommit a consumer which is called when the entry has been committed; may be null
   */
  void appendEntry(
      long lowestPosition,
      long highestPosition,
      ByteBuffer data,
      Consumer<Indexed<ZeebeEntry>> onWrite,
      Consumer<Indexed<ZeebeEntry>> onCommit);

  /**
   * Appends an entry to the local Raft log and schedules replication to each follower.
   *
   * @param lowestPosition lowest record position in the data buffer
   * @param highestPosition highest record position in the data buffer
   * @param data data to store in the entry
   */
  default void appendEntry(
      final long lowestPosition, final long highestPosition, final ByteBuffer data) {
    appendEntry(lowestPosition, highestPosition, data, null, null);
  }

  /**
   * Appends an entry to the local Raft log and schedules replication to each follower.
   *
   * @param lowestPosition lowest record position in the data buffer
   * @param highestPosition highest record position in the data buffer
   * @param data data to store in the entry
   */
  default void appendEntry(
      final long lowestPosition,
      final long highestPosition,
      final ByteBuffer data,
      final Listener listener) {
    appendEntry(lowestPosition, highestPosition, data, listener::onWrite, listener::onCommit);
  }

  /**
   * An append listener can observe and be notified of different events related to the append
   * operation.
   */
  interface Listener {

    /**
     * Called when the entry has been written to the log.
     *
     * @param indexed the entry that was written to the log
     */
    void onWrite(Indexed<ZeebeEntry> indexed);

    /**
     * Called when the entry has been committed.
     *
     * @param indexed the entry that was committed
     */
    void onCommit(Indexed<ZeebeEntry> indexed);
  }
}
```

**Comment by ChrisKujawa** [comment]
I assume it is not easy possible to register the listener once? Because now your implementation needs probably a map on which it stores per indexed entry the listener and remove this tuple after onCommit was called. This means you have more to do and higher memory consumption on contrast to register a listener only once and be called every time an index was written or committed. 

If this is not easily possible currently I'm fine with this approach for now. i would like to have a NullListener instead of the null.

**Comment by npepinpe** [comment]
Since the implementation uses futures, the listener is captured in the closure of the `whenComplete` of those futures, so no map is necessary. Registering it once would be more lightweight, but make the appender interface a little more complex/heavy, whereas now it's just a functional interface.

I can add a `NullConsumer`, I'm also not a fan of passing null, but I thought it might be nicer to have the option to use a listener or pass two callbacks; primary users for the callbacks I assume will be tests, so I guess that's a poor reason to not always use the listener :sweat_smile: If I had to pick between a single listener interface and two consumers, I'm leaning more towards the listener however, it's clearer in intent, and more flexible and future proof. So maybe I just remove the consumers entirely, and keep just this?

```java
/**
 * A log appender provides a central entry point to append to the local Raft log such that it is
 * automatically replicated and eventually committed, and the ability for callers to be notified of
 * various events, e.g. {@link Listener#onCommit(Indexed)}.
 */
@FunctionalInterface
public interface ZeebeLogAppender {

  /**
   * Appends an entry to the local Raft log and schedules replication to each follower.
   *
   * @param lowestPosition lowest record position in the data buffer
   * @param highestPosition highest record position in the data buffer
   * @param data data to store in the entry
   */
  void appendEntry(
      final long lowestPosition,
      final long highestPosition,
      final ByteBuffer data,
      final Listener listener);

  /**
   * An append listener can observe and be notified of different events related to the append
   * operation.
   */
  interface Listener {

    /**
     * Called when the entry has been written to the log.
     *
     * @param indexed the entry that was written to the log
     */
    void onWrite(Indexed<ZeebeEntry> indexed);

    /**
     * Called when the entry has been committed.
     *
     * @param indexed the entry that was committed
     */
    void onCommit(Indexed<ZeebeEntry> indexed);
  }
}
```

Maybe adding defaults here is too premature :sweat_smile:

**Comment by ChrisKujawa** [comment]
Yes I think it is much simpler. I like it more. No need to over engineer here :smile:
